#y!/bin/sh

echo `hostname` > /etc/mailname
sh files/extra-tools/etc-config-backup.sh
groupadd -g 89 vmail 2>/dev/null
useradd -g vmail -u 89 -d /home/powermail vmail 2>/dev/null

/etc/init.d/spamassassin stop 2>/dev/null
/etc/init.d/clamav-freshclam stop 2>/dev/null
/etc/init.d/clamav-daemon stop 2>/dev/null
/etc/init.d/postfix stop 2>/dev/null
/etc/init.d/dovecot stop 2>/dev/null
/etc/init.d/opendkim stop 2>/dev/null
/etc/init.d/apache2 stop 2>/dev/null



/bin/cp -pR files/rootdir/* /
/bin/cp -pR files/extra-tools/* /bin/
mkdir  /var/www/html/powermailadmin/templates_c 2>/dev/null
chmod -R 777 /var/www/html/powermailadmin/templates_c

chown -R vmail:vmail /home/powermail
chmod 755 /home/powermail/bin/*

touch /var/log/dovecot.log
chmod 666 /var/log/dovecot.log
chmod 666 /var/log/clamav/clamav.log

sed -i "s/error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT/error_reporting = E_ERROR/" /etc/php/7.0/cli/php.ini
sed -i "s/error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT/error_reporting = E_ERROR/" /etc/php/7.0/apache2/php.ini





sed -i "s/SOCKET\=local\:\$RUNDIR\/opendkim.sock/#SOCKET\=local\:\$RUNDIR\/opendkim.sock/" /etc/default/opendkim
sed -i "s/#SOCKET\=inet\:12345\@localhost/SOCKET\=inet\:12345\@localhost/" /etc/default/opendkim 
/lib/opendkim/opendkim.service.generate
systemctl daemon-reload

### use same to add for other new domain too
/bin/dkim-setup.pl `hostname`


service opendkim restart




#/etc/init.d/opendkim start
/etc/init.d/spamassassin start
/etc/init.d/clamav-freshclam start
/etc/init.d/clamav-daemon start
/etc/init.d/apache2 start

#systemctl enable spamassassin

echo "Working on importing powermail MySQL database..."

MYSQLPASSVPOP=`pwgen -c -1 8`
echo $MYSQLPASSVPOP > /usr/local/src/mysql-powermail-pass
mysqladmin create powermail -uroot 
echo "GRANT ALL PRIVILEGES ON powermail.* TO powermail@localhost IDENTIFIED BY '$MYSQLPASSVPOP'" | mysql -uroot 
mysqladmin -uroot reload
mysqladmin -uroot refresh

## disabled amavis if got install
postconf -e 'content_filter = '

mysql  <  files/powermaildb.sql

sed -i "s/ohm8ahC2/`cat /usr/local/src/mysql-powermail-pass`/" /etc/postfix/sql/mysql_relay_domains_maps.cf
sed -i "s/ohm8ahC2/`cat /usr/local/src/mysql-powermail-pass`/" /etc/postfix/sql/mysql_virtual_alias_domain_catchall_maps.cf
sed -i "s/ohm8ahC2/`cat /usr/local/src/mysql-powermail-pass`/" /etc/postfix/sql/mysql_virtual_alias_domain_mailbox_maps.cf
sed -i "s/ohm8ahC2/`cat /usr/local/src/mysql-powermail-pass`/" /etc/postfix/sql/mysql_virtual_alias_domain_maps.cf
sed -i "s/ohm8ahC2/`cat /usr/local/src/mysql-powermail-pass`/" /etc/postfix/sql/mysql_virtual_alias_maps.cf
sed -i "s/ohm8ahC2/`cat /usr/local/src/mysql-powermail-pass`/" /etc/postfix/sql/mysql_virtual_domains_maps.cf
sed -i "s/ohm8ahC2/`cat /usr/local/src/mysql-powermail-pass`/" /etc/postfix/sql/mysql_virtual_mailbox_limit_maps.cf
sed -i "s/ohm8ahC2/`cat /usr/local/src/mysql-powermail-pass`/" /etc/postfix/sql/mysql_virtual_mailbox_maps.cf
sed -i "s/ohm8ahC2/`cat /usr/local/src/mysql-powermail-pass`/" /etc/dovecot/dovecot-sql.conf.ext
sed -i "s/ohm8ahC2/`cat /usr/local/src/mysql-powermail-pass`/" /var/www/html/powermailadmin/config.inc.php 
sed -i "s/ohm8ahC2/`cat /usr/local/src/mysql-powermail-pass`/" /var/www/html/powermailadmin/config.local.php 

sed -i "s/powermail\.mydomainname\.com/`hostname`/" /etc/postfix/main.cf
sed -i "s/ohm8ahC2/`cat /usr/local/src/mysql-powermail-pass`/" /home/powermail/etc/powermail.mysql 

## default password for mysql root on debian 9 localhost is NONE
MYSQL_ROOT_PASS=""
AUTOGENERATED_PASS=`pwgen -c -1 10`

echo "roundcube-core roundcube/dbconfig-install boolean true"  | debconf-set-selections
echo "roundcube-core roundcube/app-password-confirm password $AUTOGENERATED_PASS"  | debconf-set-selections
echo "roundcube-core roundcube/mysql/app-pass password $AUTOGENERATED_PASS"  | debconf-set-selections




apt-get install -y roundcube roundcube-core roundcube-mysql roundcube-plugins roundcube-plugins-extra
sed -i "s/#    Alias \/roundcube \/var\/lib\/roundcube/    Alias \/roundcube \/var\/lib\/roundcube/" /etc/apache2/conf-enabled/roundcube.conf
sed -i "s/\$config\['default_host'\] = '';/\$config\['default_host'\] = '127.0.0.1';/" /etc/roundcube/config.inc.php
sed -i "s/\$config\['smtp_server'\] = '';/\$config\['smtp_server'\] = '127.0.0.1';/" /etc/roundcube/config.inc.php




echo "Working on importing nextcloud webmail MySQL database..."

MYSQLPASS=`pwgen -c -1 8`
echo $MYSQLPASS > /usr/local/src/mysql-nextcloud-pass
mysqladmin create nextcloud -uroot
echo "GRANT ALL PRIVILEGES ON nextcloud.* TO nextcloud@localhost IDENTIFIED BY '$MYSQLPASS'" | mysql -uroot
mysqladmin -uroot reload
mysqladmin -uroot refresh

mysql  < files/nextcloud-db.sql



#/usr/share/clamav-unofficial-sigs/conf.d/00-clamav-unofficial-sigs.conf
# disable /comment below lines in above file
#   honeynet.hdb
#   securiteinfo.hdb
#   securiteinfobat.hdb
#   securiteinfodos.hdb
#   securiteinfoelf.hdb
#   securiteinfohtml.hdb
#   securiteinfooffice.hdb
#   securiteinfopdf.hdb
#   securiteinfosh.hdb



echo > /var/log/mail.log
/bin/rm -rf /var/log/mail.info
/bin/rm -rf /var/log/mail.warn
/bin/rm -rf /var/log/mail.err
echo > /var/log/dovecot.log

/bin/rm -rf /var/www/html/nextcloud/core/skeleton/Documents/*
/bin/rm -rf /var/www/html/nextcloud/core/skeleton/Photos/*
/bin/rm -rf /var/www/html/nextcloud/core/skeleton/N*
chown -R www-data:www-data /var/www/html

NCPASS=`pwgen -c -1 8`
echo $NCPASS > /usr/local/src/nextcloudadmin-pass

echo "Nextcloud admin login: nextcloud and password $NCPASS in /usr/local/src/nextcloudadmin-pass"
cd /var/www/html/nextcloud
sudo -u www-data bash -c "export OC_PASS=$NCPASS ;php occ  user:resetpassword --password-from-env nextcloud "


/etc/init.d/postfix restart
/etc/init.d/dovecot restart
/etc/init.d/rsyslog restart

## add system domain

/home/powermail/bin/vadddomain `hostname`
/home/powermail/bin/vaddalias root@`hostname` postmaster@`hostname`
/home/powermail/bin/vaddalias clamav@`hostname` postmaster@`hostname`
/home/powermail/bin/vaddalias abuse@`hostname` postmaster@`hostname`



sendEmail -f postmaster@`hostname`  -t postmaster@`hostname` -u "Test Mail" -m "Test Mail" -o tls=no -s 127.0.0.1:25
