#!/bin/sh

## default password for mysql root on debian 9 localhost is NONE
MYSQL_ROOT_PASS=""
AUTOGENERATED_PASS=`pwgen -c -1 10`

##### only if default Roundcube webmail is needed
echo "roundcube-core roundcube/dbconfig-install boolean true"  | debconf-set-selections
echo "roundcube-core roundcube/app-password-confirm password $AUTOGENERATED_PASS"  | debconf-set-selections
cho "roundcube-core roundcube/mysql/app-pass password $AUTOGENERATED_PASS"  | debconf-set-selections
apt-get install -y roundcube roundcube-core roundcube-mysql roundcube-plugins roundcube-plugins-extra
sed -i "s/#    Alias \/roundcube \/var\/lib\/roundcube/    Alias \/roundcube \/var\/lib\/roundcube/" /etc/apache2/conf-enabled/roundcube.conf
sed -i "s/\$config\['default_host'\] = '';/\$config\['default_host'\] = '127.0.0.1';/" /etc/roundcube/config.inc.php
sed -i "s/\$config\['smtp_server'\] = '';/\$config\['smtp_server'\] = '127.0.0.1';/" /etc/roundcube/config.inc.php


